server:
  AppVersion: 1.0.0
  Port: :8060
  ReadTimeout: 10
  WriteTimeout: 10

postgres:
  PostgresqlHost: postgres
  PostgresqlPort: 5432
  PostgresqlUser: program
  PostgresqlPassword: test
  PostgresqlDbname: payments